robot:
  id: waference@appspot.com
  name: waference
  image_url: 
  profile_url: 
  version: 1
appcfg:
  version: 1
# Uncomment this section to add gems required by your robot.
# They will unpacked in your project at appengine deploy time
# gems:
#  - some_gem         # Replace this with the name of the gem you require
#  - some_other_gem   # Replace this with the name of the gem you require
